description: Global settings for administrative accounts.
properties:
  lockout_duration:
    description: The lockout duration, in milliseconds, if a user is locked out after
      reaching the maximum number of login attempts. Ranges from 1 second to 90 days.
    example: 3600000
    format: int64
    maximum: 7776000000
    minimum: 1000
    type: integer
  max_login_attempts:
    description: Maximum number of failed login attempts allowed before the user is
      locked out.
    example: 10
    format: int32
    maximum: 20
    minimum: 1
    type: integer
  min_password_length:
    description: Minimum password length. If not specified, defaults to 1.
    example: 1
    format: int32
    type: integer
  single_sign_on_enabled:
    description: If `true`, then single sign-on is enabled for the array.
    example: true
    type: boolean
type: object
