consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.2/admin.yaml
  Alert:
    $ref: ../models/FB1.2/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.2/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.2/alert-watcher-test.yaml
  Array:
    $ref: ../models/FB1.3/array.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.3/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Blade:
    $ref: ../models/FB1.2/blade.yaml
  Bucket:
    $ref: ../models/FB1.3/bucket.yaml
  Certificate:
    $ref: ../models/FB1.2/certificate.yaml
  DNS:
    $ref: ../models/FB1.2/dns.yaml
  DirectoryService:
    $ref: ../models/FB1.3/directory-service.yaml
  FileSystem:
    $ref: ../models/FB1.2/file-system.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.1/file-system-snapshot.yaml
  Hardware:
    $ref: ../models/FB1.3/hardware.yaml
  HardwareConnector:
    $ref: ../models/FB1.3/hardware-connector.yaml
  LinkAggregationGroup:
    $ref: ../models/FB1.3/link-aggregation-group.yaml
  NetworkInterface:
    $ref: ../models/FB1.3/network-interface.yaml
  ObjectStoreAccessKey:
    $ref: ../models/FB1.3/object-store-access-key.yaml
  ObjectStoreAccount:
    $ref: ../models/FB1.3/object-store-account.yaml
  ObjectStoreUser:
    $ref: ../models/FB1.3/object-store-user.yaml
  SMTP:
    $ref: ../models/FB1.3/smtp.yaml
  Subnet:
    $ref: ../models/FB1.3/subnet.yaml
  TestResult:
    $ref: ../models/FB1.3/test-result.yaml
info:
  description: A lightweight client for FlashBlade REST API 1.3, developed by Pure
    Storage, Inc. (http://www.purestorage.com/).
  title: FlashBlade REST API Client
  version: 1.3
paths:
  /api/1.3/admins:
    $ref: ../paths/FB1.2/admins.path.yaml
  /api/1.3/alert-watchers:
    $ref: ../paths/FB1.2/alert-watchers.path.yaml
  /api/1.3/alert-watchers/test:
    $ref: ../paths/FB1.2/alert-watchers-test.path.yaml
  /api/1.3/alerts:
    $ref: ../paths/FB1.2/alerts.path.yaml
  /api/1.3/arrays:
    $ref: ../paths/FB1.3/arrays.path.yaml
  /api/1.3/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /api/1.3/arrays/performance:
    $ref: ../paths/FB1.3/arrays-performance.path.yaml
  /api/1.3/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /api/1.3/arrays/space:
    $ref: ../paths/FB1.2/arrays-space.path.yaml
  /api/1.3/blades:
    $ref: ../paths/FB1.2/blades.path.yaml
  /api/1.3/buckets:
    $ref: ../paths/FB1.3/buckets.path.yaml
  /api/1.3/certificates:
    $ref: ../paths/FB1.2/certificates.path.yaml
  /api/1.3/directory-services:
    $ref: ../paths/FB1.3/directory-services.path.yaml
  /api/1.3/directory-services/test:
    $ref: ../paths/FB1.3/directory-service-test.path.yaml
  /api/1.3/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /api/1.3/file-system-snapshots:
    $ref: ../paths/FB1.1/file-system-snapshots.path.yaml
  /api/1.3/file-systems:
    $ref: ../paths/FB1.2/file-systems.path.yaml
  /api/1.3/hardware:
    $ref: ../paths/FB1.3/hardware.path.yaml
  /api/1.3/hardware-connectors:
    $ref: ../paths/FB1.3/hardware-connectors.path.yaml
  /api/1.3/link-aggregation-groups:
    $ref: ../paths/FB1.3/link-aggregation-groups.path.yaml
  /api/1.3/network-interfaces:
    $ref: ../paths/FB1.3/network-interfaces.path.yaml
  /api/1.3/object-store-access-keys:
    $ref: ../paths/FB1.3/object-store-access-keys.path.yaml
  /api/1.3/object-store-accounts:
    $ref: ../paths/FB1.3/object-store-accounts.path.yaml
  /api/1.3/object-store-users:
    $ref: ../paths/FB1.3/object-store-users.path.yaml
  /api/1.3/smtp:
    $ref: ../paths/FB1.3/smtp.path.yaml
  /api/1.3/subnets:
    $ref: ../paths/FB1.3/subnets.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    $ref: ../paths/FB1.0/login.path.yaml
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: Authorization
- name: Administrators
- name: Alerts
- name: Alert Watchers
- name: Arrays
- name: Blades
- name: Buckets
- name: Certificates
- name: Directory Services
- name: DNS
- name: File Systems
- name: File System Snapshots
- name: Hardware
- name: Hardware Connectors
- name: Link Aggregation Groups
- name: Network Interfaces
- name: Object Store Access Keys
- name: Object Store Accounts
- name: Object Store Users
- name: SMTP
- name: Subnets
