consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.2/admin.yaml
  AdminCache:
    $ref: ../models/FB1.4/admin-cache.yaml
  Alert:
    $ref: ../models/FB1.2/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.2/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.2/alert-watcher-test.yaml
  Array:
    $ref: ../models/FB1.7/array.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.3/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Blade:
    $ref: ../models/FB1.2/blade.yaml
  Bucket:
    $ref: ../models/FB1.6/bucket.yaml
  Certificate:
    $ref: ../models/FB1.2/certificate.yaml
  ClientPerformance:
    $ref: ../models/FB1.4/client-performance.yaml
  DNS:
    $ref: ../models/FB1.2/dns.yaml
  DirectoryService:
    $ref: ../models/FB1.7/directory-service.yaml
  DirectoryServiceRole:
    $ref: ../models/FB1.4/directory-service-role.yaml
  FileSystem:
    $ref: ../models/FB1.6/file-system.yaml
  FileSystemPerformance:
    $ref: ../models/FB1.5/file-system-performance.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.1/file-system-snapshot.yaml
  GroupQuota:
    $ref: ../models/FB1.6/group-quota.yaml
  Hardware:
    $ref: ../models/FB1.3/hardware.yaml
  HardwareConnector:
    $ref: ../models/FB1.3/hardware-connector.yaml
  LinkAggregationGroup:
    $ref: ../models/FB1.5/link-aggregation-group.yaml
  NetworkInterface:
    $ref: ../models/FB1.5/network-interface.yaml
  ObjectStoreAccessKey:
    $ref: ../models/FB1.5/object-store-access-key.yaml
  ObjectStoreAccount:
    $ref: ../models/FB1.4/object-store-account.yaml
  ObjectStoreUser:
    $ref: ../models/FB1.5/object-store-user.yaml
  Policy:
    $ref: ../models/FB1.5/policy.yaml
  SMTP:
    $ref: ../models/FB1.3/smtp.yaml
  Subnet:
    $ref: ../models/FB1.5/subnet.yaml
  Support:
    $ref: ../models/FB1.6/support.yaml
  TestResult:
    $ref: ../models/FB1.3/test-result.yaml
  UserQuota:
    $ref: ../models/FB1.6/user-quota.yaml
info:
  description: A lightweight client for FlashBlade REST API 1.7, developed by Pure
    Storage, Inc. (http://www.purestorage.com/).
  title: FlashBlade REST API Client
  version: 1.7
paths:
  /api/1.7/admins:
    $ref: ../paths/FB1.2/admins.path.yaml
  /api/1.7/admins/cache:
    $ref: ../paths/FB1.4/admins-cache.path.yaml
  /api/1.7/alert-watchers:
    $ref: ../paths/FB1.2/alert-watchers.path.yaml
  /api/1.7/alert-watchers/test:
    $ref: ../paths/FB1.2/alert-watchers-test.path.yaml
  /api/1.7/alerts:
    $ref: ../paths/FB1.2/alerts.path.yaml
  /api/1.7/arrays:
    $ref: ../paths/FB1.7/arrays.path.yaml
  /api/1.7/arrays/clients/performance:
    $ref: ../paths/FB1.4/clients-performance.path.yaml
  /api/1.7/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /api/1.7/arrays/performance:
    $ref: ../paths/FB1.3/arrays-performance.path.yaml
  /api/1.7/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /api/1.7/arrays/space:
    $ref: ../paths/FB1.2/arrays-space.path.yaml
  /api/1.7/blades:
    $ref: ../paths/FB1.2/blades.path.yaml
  /api/1.7/buckets:
    $ref: ../paths/FB1.6/buckets.path.yaml
  /api/1.7/certificates:
    $ref: ../paths/FB1.2/certificates.path.yaml
  /api/1.7/directory-services:
    $ref: ../paths/FB1.7/directory-services.path.yaml
  /api/1.7/directory-services/roles:
    $ref: ../paths/FB1.4/directory-service-roles.path.yaml
  /api/1.7/directory-services/test:
    $ref: ../paths/FB1.3/directory-service-test.path.yaml
  /api/1.7/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /api/1.7/file-system-snapshots:
    $ref: ../paths/FB1.5/file-system-snapshots.path.yaml
  /api/1.7/file-systems:
    $ref: ../paths/FB1.6/file-systems.path.yaml
  /api/1.7/file-systems-snapshots/policies:
    $ref: ../paths/FB1.5/file-system-snapshots-policies.path.yaml
  /api/1.7/file-systems/performance:
    $ref: ../paths/FB1.5/file-systems-performance.path.yaml
  /api/1.7/file-systems/policies:
    $ref: ../paths/FB1.5/file-systems-policies.path.yaml
  /api/1.7/hardware:
    $ref: ../paths/FB1.3/hardware.path.yaml
  /api/1.7/hardware-connectors:
    $ref: ../paths/FB1.3/hardware-connectors.path.yaml
  /api/1.7/link-aggregation-groups:
    $ref: ../paths/FB1.5/link-aggregation-groups.path.yaml
  /api/1.7/logs:
    $ref: ../paths/FB1.4/logs.path.yaml
  /api/1.7/network-interfaces:
    $ref: ../paths/FB1.5/network-interfaces.path.yaml
  /api/1.7/object-store-access-keys:
    $ref: ../paths/FB1.5/object-store-access-keys.path.yaml
  /api/1.7/object-store-accounts:
    $ref: ../paths/FB1.4/object-store-accounts.path.yaml
  /api/1.7/object-store-users:
    $ref: ../paths/FB1.5/object-store-users.path.yaml
  /api/1.7/policies:
    $ref: ../paths/FB1.5/policies.path.yaml
  /api/1.7/policies/file-system-snapshots:
    $ref: ../paths/FB1.5/policies-file-system-snapshots.path.yaml
  /api/1.7/policies/file-systems:
    $ref: ../paths/FB1.5/policies-file-systems.path.yaml
  /api/1.7/policies/members:
    $ref: ../paths/FB1.5/policies-members.path.yaml
  /api/1.7/quotas/groups:
    $ref: ../paths/FB1.6/quotas-groups.path.yaml
  /api/1.7/quotas/users:
    $ref: ../paths/FB1.6/quotas-users.path.yaml
  /api/1.7/smtp:
    $ref: ../paths/FB1.3/smtp.path.yaml
  /api/1.7/subnets:
    $ref: ../paths/FB1.5/subnets.path.yaml
  /api/1.7/support:
    $ref: ../paths/FB1.6/support.path.yaml
  /api/1.7/support/test:
    $ref: ../paths/FB1.6/support-test.path.yaml
  /api/1.7/usage/groups:
    $ref: ../paths/FB1.6/usage-groups.path.yaml
  /api/1.7/usage/users:
    $ref: ../paths/FB1.6/usage-users.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    $ref: ../paths/FB1.0/login.path.yaml
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: Authorization
- name: Administrators
- name: Alerts
- name: Alert Watchers
- name: Arrays
- name: Blades
- name: Buckets
- name: Certificates
- name: Clients
- name: Directory Services
- name: DNS
- name: File Systems
- name: File System Snapshots
- name: Hardware
- name: Hardware Connectors
- name: Link Aggregation Groups
- name: Logs
- name: Network Interfaces
- name: Object Store Access Keys
- name: Object Store Accounts
- name: Object Store Users
- name: Policies
- name: Quotas
- name: SMTP
- name: Subnets
- name: Support
