basePath: /api
consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.8/admin.yaml
  AdminCache:
    $ref: ../models/FB1.8/admin-cache.yaml
  Alert:
    $ref: ../models/FB1.8/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.8/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.2/alert-watcher-test.yaml
  Array:
    $ref: ../models/FB1.7/array.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.3/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Blade:
    $ref: ../models/FB1.2/blade.yaml
  Bucket:
    $ref: ../models/FB1.8/bucket.yaml
  BucketPerformance:
    $ref: ../models/FB1.8/bucket-performance.yaml
  BucketS3SpecificPerformance:
    $ref: ../models/FB1.8/bucket-s3-specific-performance.yaml
  Certificate:
    $ref: ../models/FB1.8/certificate.yaml
  CertificateGroup:
    $ref: ../models/FB1.8/certificate-group.yaml
  CertificateGroupUse:
    $ref: ../models/FB1.8/certificate-group-use.yaml
  CertificateUse:
    $ref: ../models/FB1.8/certificate-use.yaml
  ClientPerformance:
    $ref: ../models/FB1.4/client-performance.yaml
  DNS:
    $ref: ../models/FB1.2/dns.yaml
  DirectoryService:
    $ref: ../models/FB1.8/directory-service.yaml
  DirectoryServiceRole:
    $ref: ../models/FB1.8/directory-service-role.yaml
  FileSystem:
    $ref: ../models/FB1.8/file-system.yaml
  FileSystemPerformance:
    $ref: ../models/FB1.5/file-system-performance.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.8/file-system-snapshot.yaml
  GroupQuota:
    $ref: ../models/FB1.8/group-quota.yaml
  Hardware:
    $ref: ../models/FB1.8/hardware.yaml
  HardwareConnector:
    $ref: ../models/FB1.8/hardware-connector.yaml
  LinkAggregationGroup:
    $ref: ../models/FB1.8/link-aggregation-group.yaml
  Member:
    $ref: ../models/FB1.8/member.yaml
  NetworkInterface:
    $ref: ../models/FB1.8/network-interface.yaml
  ObjectStoreAccessKey:
    $ref: ../models/FB1.8/object-store-access-key.yaml
  ObjectStoreAccount:
    $ref: ../models/FB1.8/object-store-account.yaml
  ObjectStoreUser:
    $ref: ../models/FB1.8/object-store-user.yaml
  Policy:
    $ref: ../models/FB1.8/policy.yaml
  QuotaSetting:
    $ref: ../models/FB1.8/quota-setting.yaml
  SMTP:
    $ref: ../models/FB1.3/smtp.yaml
  Subnet:
    $ref: ../models/FB1.8/subnet.yaml
  Support:
    $ref: ../models/FB1.8/support.yaml
  TestResult:
    $ref: ../models/FB1.3/test-result.yaml
  UserQuota:
    $ref: ../models/FB1.8/user-quota.yaml
host: irvm-tsteele.dev.purestorage.com:8091
info:
  description: "## Pure Confidential and Proprietary. May be subject to NDA and/or\
    \ End User Agreement.\nA light weight tool to explore the API for FlashBlade,\
    \ community supported.  \nFor help with this tool, use [Pure1 Community](https://community.purestorage.com/)\
    \ or the [code-purestorage Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)\n\
    \n## Authentication\nUse an api-token (header param) to start a session at /api/login,\
    \ that returns an x-auth-token header which expires in 30 minutes by default.\
    \ This is\ndifferent than FlashArray, which uses a cookie instead.  The x-auth-token\
    \ is saved and added by the built in proxy server.\n\nUse \"pureadmin create --api-token\"\
    \ on the CLI to create an API Token.  Or use \"pureadmin list --api-token --expose\"\
    \ to show a token already created.  Note, it only shows tokens for user that is\
    \ logged in.\n\n## Proxy\nThis Swagger tool includes a proxy server that forwards\
    \ API calls to the array.  In the Swagger UI, you will \\\nsee curl API calls\
    \ to IP 127.0.0.1, that is the proxy server. To see the API call details view\
    \ the console output.\n\n## Error Codes\nUse HTTP Response codes to determine\
    \ command results.  Error message json formats are different depending on the\
    \ endpoint.\n\n## Official Documention\nGo to the Pure support portal for the\
    \ [full documentation](https://support.purestorage.com/FlashBlade/Purity_FB/Purity%2F%2F%2F%2FFB_REST_API/Management_REST_API/Management_REST_API_Reference_Guides)."
  title: FlashBlade REST API Client
  version: 1.8
paths:
  /1.8/api/1.8/admins:
    $ref: ../paths/FB1.8/admins.path.yaml
  /1.8/api/1.8/admins/cache:
    $ref: ../paths/FB1.8/admins-cache.path.yaml
  /1.8/api/1.8/alert-watchers:
    $ref: ../paths/FB1.8/alert-watchers.path.yaml
  /1.8/api/1.8/alert-watchers/test:
    $ref: ../paths/FB1.2/alert-watchers-test.path.yaml
  /1.8/api/1.8/alerts:
    $ref: ../paths/FB1.8/alerts.path.yaml
  /1.8/api/1.8/arrays:
    $ref: ../paths/FB1.7/arrays.path.yaml
  /1.8/api/1.8/arrays/clients/performance:
    $ref: ../paths/FB1.4/clients-performance.path.yaml
  /1.8/api/1.8/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /1.8/api/1.8/arrays/performance:
    $ref: ../paths/FB1.3/arrays-performance.path.yaml
  /1.8/api/1.8/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /1.8/api/1.8/arrays/space:
    $ref: ../paths/FB1.2/arrays-space.path.yaml
  /1.8/api/1.8/blades:
    $ref: ../paths/FB1.8/blades.path.yaml
  /1.8/api/1.8/buckets:
    $ref: ../paths/FB1.8/buckets.path.yaml
  /1.8/api/1.8/buckets/performance:
    $ref: ../paths/FB1.8/buckets-performance.path.yaml
  /1.8/api/1.8/buckets/s3-specific-performance:
    $ref: ../paths/FB1.8/buckets-s3-specific-performance.path.yaml
  /1.8/api/1.8/certificate-groups:
    $ref: ../paths/FB1.8/certificate-groups.path.yaml
  /1.8/api/1.8/certificate-groups/certificates:
    $ref: ../paths/FB1.8/certificate-groups-certificates.path.yaml
  /1.8/api/1.8/certificate-groups/uses:
    $ref: ../paths/FB1.8/certificate-groups-uses.path.yaml
  /1.8/api/1.8/certificates:
    $ref: ../paths/FB1.8/certificates.path.yaml
  /1.8/api/1.8/certificates/certificate-groups:
    $ref: ../paths/FB1.8/certificates-certificate-groups.path.yaml
  /1.8/api/1.8/certificates/uses:
    $ref: ../paths/FB1.8/certificates-uses.path.yaml
  /1.8/api/1.8/directory-services:
    $ref: ../paths/FB1.8/directory-services.path.yaml
  /1.8/api/1.8/directory-services/roles:
    $ref: ../paths/FB1.8/directory-service-roles.path.yaml
  /1.8/api/1.8/directory-services/test:
    $ref: ../paths/FB1.8/directory-service-test.path.yaml
  /1.8/api/1.8/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /1.8/api/1.8/file-system-snapshots:
    $ref: ../paths/FB1.8/file-system-snapshots.path.yaml
  /1.8/api/1.8/file-systems:
    $ref: ../paths/FB1.8/file-systems.path.yaml
  /1.8/api/1.8/file-systems-snapshots/policies:
    $ref: ../paths/FB1.8/file-system-snapshots-policies.path.yaml
  /1.8/api/1.8/file-systems/performance:
    $ref: ../paths/FB1.5/file-systems-performance.path.yaml
  /1.8/api/1.8/file-systems/policies:
    $ref: ../paths/FB1.8/file-systems-policies.path.yaml
  /1.8/api/1.8/hardware:
    $ref: ../paths/FB1.8/hardware.path.yaml
  /1.8/api/1.8/hardware-connectors:
    $ref: ../paths/FB1.8/hardware-connectors.path.yaml
  /1.8/api/1.8/link-aggregation-groups:
    $ref: ../paths/FB1.8/link-aggregation-groups.path.yaml
  /1.8/api/1.8/logs:
    $ref: ../paths/FB1.4/logs.path.yaml
  /1.8/api/1.8/network-interfaces:
    $ref: ../paths/FB1.8/network-interfaces.path.yaml
  /1.8/api/1.8/object-store-access-keys:
    $ref: ../paths/FB1.8/object-store-access-keys.path.yaml
  /1.8/api/1.8/object-store-accounts:
    $ref: ../paths/FB1.8/object-store-accounts.path.yaml
  /1.8/api/1.8/object-store-users:
    $ref: ../paths/FB1.8/object-store-users.path.yaml
  /1.8/api/1.8/policies:
    $ref: ../paths/FB1.8/policies.path.yaml
  /1.8/api/1.8/policies/file-system-snapshots:
    $ref: ../paths/FB1.8/policies-file-system-snapshots.path.yaml
  /1.8/api/1.8/policies/file-systems:
    $ref: ../paths/FB1.8/policies-file-systems.path.yaml
  /1.8/api/1.8/policies/members:
    $ref: ../paths/FB1.8/policies-members.path.yaml
  /1.8/api/1.8/quotas/groups:
    $ref: ../paths/FB1.8/quotas-groups.path.yaml
  /1.8/api/1.8/quotas/settings:
    $ref: ../paths/FB1.8/quotas-settings.path.yaml
  /1.8/api/1.8/quotas/users:
    $ref: ../paths/FB1.8/quotas-users.path.yaml
  /1.8/api/1.8/smtp:
    $ref: ../paths/FB1.3/smtp.path.yaml
  /1.8/api/1.8/subnets:
    $ref: ../paths/FB1.8/subnets.path.yaml
  /1.8/api/1.8/support:
    $ref: ../paths/FB1.8/support.path.yaml
  /1.8/api/1.8/support/test:
    $ref: ../paths/FB1.6/support-test.path.yaml
  /1.8/api/1.8/usage/groups:
    $ref: ../paths/FB1.8/usage-groups.path.yaml
  /1.8/api/1.8/usage/users:
    $ref: ../paths/FB1.8/usage-users.path.yaml
  /1.8/api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /1.8/api/login:
    $ref: ../paths/FB1.0/login.path.yaml
  /1.8/api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
  /api_version:
    get:
      description: Lists supported API versions on this array.
      responses:
        200:
          description: List supported API versions
      tags:
      - api
  /login:
    post:
      description: Create a new session with API_KEY
      parameters:
      - in: header
        name: api-token
        required: true
        type: string
      responses:
        200:
          description: User logged in
          headers:
            x-auth-token:
              description: authentication token, pass this back for future API Calls.
              type: string
          schema:
            example:
              username: pureuser
            properties:
              username:
                description: The user name logged in.
                type: string
            type: object
      tags:
      - auth
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: api
- name: auth
- name: authentication
- name: admins
- name: alerts
- name: alert-watchers
- name: arrays
- name: blades
- name: buckets
- name: certificates
- name: certificate-groups
- name: clients
- name: directory-services
- name: dns
- name: file-systems
- name: file-system-snapshots
- name: hardware
- name: hardware-connectors
- name: link-aggregation-groups
- name: logs
- name: network-interfaces
- name: object-store-access-keys
- name: object-store-accounts
- name: object-store-users
- name: policies
- name: quotas
- name: smtp
- name: subnets
- name: support
