basePath: /
consumes:
- application/json
definitions:
  FileSystem:
    $ref: ../models/FB1.0/file-system.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.0/file-system-snapshot.yaml
info:
  description: "## Pure Swagger UI for FlashBlade\nA light weight tool to explore\
    \ the API for FlashBlade, community supported.  \nFor help with this tool, use\
    \ [Pure1 Community](https://community.purestorage.com/) or the [code-purestorage\
    \ Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)\n\
    \n## Authentication\nUse an api-token (header param) to start a session at /api/login,\
    \ that returns an x-auth-token header which expires in 30 minutes by default.\
    \ This is\ndifferent than FlashArray, which uses a cookie instead.  The x-auth-token\
    \ is saved and added by the built in proxy server.\n\nUse \"pureadmin create --api-token\"\
    \ on the CLI to create an API Token.  Or use \"pureadmin list --api-token --expose\"\
    \ to show a token already created.  Note, it only shows tokens for user that is\
    \ logged in.\n\n## Proxy\nThis Swagger tool includes a proxy server that forwards\
    \ API calls to the array.  In the Swagger UI, you will \\\nsee curl API calls\
    \ to IP 127.0.0.1, that is the proxy server. To see the API call details view\
    \ the console output.\n\n## Error Codes\nUse HTTP Response codes to determine\
    \ command results.  Error message json formats are different depending on the\
    \ endpoint.\n\n## Official Documention\nGo to the Pure support portal for the\
    \ [full documentation](https://support.purestorage.com/FlashBlade/Purity_FB/Purity%2F%2F%2F%2FFB_REST_API/Management_REST_API/Management_REST_API_Reference_Guides)."
  title: FlashBlade REST API Client
  version: 1.0
paths:
  /api/1.0/file-system-snapshots:
    $ref: ../paths/FB1.0/file-system-snapshots.path.yaml
  /api/1.0/file-systems:
    $ref: ../paths/FB1.0/file-systems.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    post:
      description: Create a new session with API_KEY
      parameters:
      - in: header
        name: api-token
        required: true
        type: string
      responses:
        200:
          description: User logged in
          headers:
            x-auth-token:
              description: authentication token, pass this back for future API Calls.
              type: string
          schema:
            example:
              username: pureuser
            properties:
              username:
                description: The user name logged in.
                type: string
            type: object
      tags:
      - auth
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: api
- name: auth
- name: Authorization
- name: File Systems
