consumes:
- application/json
definitions:
  Admin:
    $ref: ../models/FB1.2/admin.yaml
  Alert:
    $ref: ../models/FB1.2/alert.yaml
  AlertWatcher:
    $ref: ../models/FB1.2/alert-watcher.yaml
  AlertWatcherTest:
    $ref: ../models/FB1.2/alert-watcher-test.yaml
  Array:
    $ref: ../models/FB1.3/array.yaml
  ArrayHttpSpecificPerformance:
    $ref: ../models/FB1.2/array-http-specific-performance.yaml
  ArrayPerformance:
    $ref: ../models/FB1.3/array-performance.yaml
  ArrayS3SpecificPerformance:
    $ref: ../models/FB1.2/array-s3-specific-performance.yaml
  ArraySpace:
    $ref: ../models/FB1.2/array-space.yaml
  Blade:
    $ref: ../models/FB1.2/blade.yaml
  Bucket:
    $ref: ../models/FB1.3/bucket.yaml
  Certificate:
    $ref: ../models/FB1.2/certificate.yaml
  DNS:
    $ref: ../models/FB1.2/dns.yaml
  DirectoryService:
    $ref: ../models/FB1.3/directory-service.yaml
  FileSystem:
    $ref: ../models/FB1.2/file-system.yaml
  FileSystemSnapshot:
    $ref: ../models/FB1.1/file-system-snapshot.yaml
  Hardware:
    $ref: ../models/FB1.3/hardware.yaml
  HardwareConnector:
    $ref: ../models/FB1.3/hardware-connector.yaml
  LinkAggregationGroup:
    $ref: ../models/FB1.3/link-aggregation-group.yaml
  NetworkInterface:
    $ref: ../models/FB1.3/network-interface.yaml
  ObjectStoreAccessKey:
    $ref: ../models/FB1.3/object-store-access-key.yaml
  ObjectStoreAccount:
    $ref: ../models/FB1.3/object-store-account.yaml
  ObjectStoreUser:
    $ref: ../models/FB1.3/object-store-user.yaml
  SMTP:
    $ref: ../models/FB1.3/smtp.yaml
  Subnet:
    $ref: ../models/FB1.3/subnet.yaml
  TestResult:
    $ref: ../models/FB1.3/test-result.yaml
info:
  description: "## Pure Swagger UI for FlashBlade\nA light weight tool to explore\
    \ the API for FlashBlade, community supported.  \nFor help with this tool, use\
    \ [Pure1 Community](https://community.purestorage.com/) or the [code-purestorage\
    \ Slack](https://community.purestorage.com/discussion/9561/join-the-new-pure-code-slack-team-for-api-and-extensibility-discussions)\n\
    \n## Authentication\nUse an api-token (header param) to start a session at /api/login,\
    \ that returns an x-auth-token header which expires in 30 minutes by default.\
    \ This is\ndifferent than FlashArray, which uses a cookie instead.  The x-auth-token\
    \ is saved and added by the built in proxy server.\n\nUse \"pureadmin create --api-token\"\
    \ on the CLI to create an API Token.  Or use \"pureadmin list --api-token --expose\"\
    \ to show a token already created.  Note, it only shows tokens for user that is\
    \ logged in.\n\n## Proxy\nThis Swagger tool includes a proxy server that forwards\
    \ API calls to the array.  In the Swagger UI, you will \\\nsee curl API calls\
    \ to IP 127.0.0.1, that is the proxy server. To see the API call details view\
    \ the console output.\n\n## Error Codes\nUse HTTP Response codes to determine\
    \ command results.  Error message json formats are different depending on the\
    \ endpoint.\n\n## Official Documention\nGo to the Pure support portal for the\
    \ [full documentation](https://support.purestorage.com/FlashBlade/Purity_FB/Purity%2F%2F%2F%2FFB_REST_API/Management_REST_API/Management_REST_API_Reference_Guides)."
  title: FlashBlade REST API Client
  version: 1.3
paths:
  /api/1.3/admins:
    $ref: ../paths/FB1.2/admins.path.yaml
  /api/1.3/alert-watchers:
    $ref: ../paths/FB1.2/alert-watchers.path.yaml
  /api/1.3/alert-watchers/test:
    $ref: ../paths/FB1.2/alert-watchers-test.path.yaml
  /api/1.3/alerts:
    $ref: ../paths/FB1.2/alerts.path.yaml
  /api/1.3/arrays:
    $ref: ../paths/FB1.3/arrays.path.yaml
  /api/1.3/arrays/http-specific-performance:
    $ref: ../paths/FB1.2/arrays-http-specific-performance.path.yaml
  /api/1.3/arrays/performance:
    $ref: ../paths/FB1.3/arrays-performance.path.yaml
  /api/1.3/arrays/s3-specific-performance:
    $ref: ../paths/FB1.2/arrays-s3-specific-performance.path.yaml
  /api/1.3/arrays/space:
    $ref: ../paths/FB1.2/arrays-space.path.yaml
  /api/1.3/blades:
    $ref: ../paths/FB1.2/blades.path.yaml
  /api/1.3/buckets:
    $ref: ../paths/FB1.3/buckets.path.yaml
  /api/1.3/certificates:
    $ref: ../paths/FB1.2/certificates.path.yaml
  /api/1.3/directory-services:
    $ref: ../paths/FB1.3/directory-services.path.yaml
  /api/1.3/directory-services/test:
    $ref: ../paths/FB1.3/directory-service-test.path.yaml
  /api/1.3/dns:
    $ref: ../paths/FB1.2/dns.path.yaml
  /api/1.3/file-system-snapshots:
    $ref: ../paths/FB1.1/file-system-snapshots.path.yaml
  /api/1.3/file-systems:
    $ref: ../paths/FB1.2/file-systems.path.yaml
  /api/1.3/hardware:
    $ref: ../paths/FB1.3/hardware.path.yaml
  /api/1.3/hardware-connectors:
    $ref: ../paths/FB1.3/hardware-connectors.path.yaml
  /api/1.3/link-aggregation-groups:
    $ref: ../paths/FB1.3/link-aggregation-groups.path.yaml
  /api/1.3/network-interfaces:
    $ref: ../paths/FB1.3/network-interfaces.path.yaml
  /api/1.3/object-store-access-keys:
    $ref: ../paths/FB1.3/object-store-access-keys.path.yaml
  /api/1.3/object-store-accounts:
    $ref: ../paths/FB1.3/object-store-accounts.path.yaml
  /api/1.3/object-store-users:
    $ref: ../paths/FB1.3/object-store-users.path.yaml
  /api/1.3/smtp:
    $ref: ../paths/FB1.3/smtp.path.yaml
  /api/1.3/subnets:
    $ref: ../paths/FB1.3/subnets.path.yaml
  /api/api_version:
    $ref: ../paths/FB1.0/api_version.path.yaml
  /api/login:
    post:
      description: Create a new session with API_KEY
      parameters:
      - in: header
        name: api-token
        required: true
        type: string
      responses:
        200:
          description: User logged in
          headers:
            x-auth-token:
              description: authentication token, pass this back for future API Calls.
              type: string
          schema:
            example:
              username: pureuser
            properties:
              username:
                description: The user name logged in.
                type: string
            type: object
      tags:
      - Authorization
  /api/logout:
    $ref: ../paths/FB1.0/logout.path.yaml
produces:
- application/json
schemes:
- http
- https
security:
- AuthorizationHeader: []
securityDefinitions:
  ApiToken:
    in: header
    name: api-token
    type: apiKey
  AuthorizationHeader:
    in: header
    name: x-auth-token
    type: apiKey
swagger: '2.0'
tags:
- name: Authorization
- name: Administrators
- name: Alerts
- name: Alert Watchers
- name: Arrays
- name: Blades
- name: Buckets
- name: Certificates
- name: Directory Services
- name: DNS
- name: File Systems
- name: File System Snapshots
- name: Hardware
- name: Hardware Connectors
- name: Link Aggregation Groups
- name: Network Interfaces
- name: Object Store Access Keys
- name: Object Store Accounts
- name: Object Store Users
- name: SMTP
- name: Subnets
