get:
  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.8/quota-setting-get-response.yaml

  tags:
  - quotas

patch:
  parameters:
  - name: quota-setting
    in: body
    required: true
    schema:
      $ref: ../../models/FB1.8/quota-setting.yaml

  responses:
    200:
      description: OK
      schema:
        $ref: ../../responses/FB1.8/quota-setting-response.yaml

  tags:
  - quotas
