allOf:
- description: Global settings for syslog servers.
- $ref: ../../models/FB1.8/_built-in.yaml
- properties:
    ca_certificate:
      allOf:
      - $ref: ../../models/FB1.8/_reference.yaml
      - description: CA certificate used to validate the authenticity of the configured
          servers.
    ca_certificate_group:
      allOf:
      - $ref: ../../models/FB1.8/_reference.yaml
      - description: A certificate group containing CA certificates that can be used
          to validate the authenticity of the configured servers.
